# Generated by Django 5.1.7 on 2025-03-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todlist',
            new_name='Todolist',
        ),
    ]
